

CREATE TABLE CATEGORIAS
  (ID_CAT NUMBER(2) CONSTRAINT CAT_ID_PK  PRIMARY KEY, 
   TITULO VARCHAR2 (50) NOT NULL UNIQUE);



CREATE TABLE PREGUNTAS
  (ID_PREG          NUMBER(4) CONSTRAINT PREG_ID_PK PRIMARY KEY,
   ENUNCIADO        VARCHAR2 (100) NOT NULL,
   CATEGORIA_ID_PREG NUMBER(4) NOT NULL,
   CONSTRAINT PREGUNTAS_CAT_FK FOREIGN KEY ( CATEGORIA_ID_PREG )REFERENCES CATEGORIAS ON DELETE CASCADE);



CREATE TABLE RESPUESTAS
  (ID_RESP          NUMBER(4) CONSTRAINT RESP_ID_PK PRIMARY KEY,
   RESPUESTA        VARCHAR2 (250) NOT NULL ,
   ACERTADA         NUMBER(1) NOT NULL ,
   PREGUNTA_ID_CAT NUMBER(4) NOT NULL, 
   CONSTRAINT RESPUESTAS_PREGUNTA_FK FOREIGN KEY ( PREGUNTA_ID_CAT ) REFERENCES PREGUNTAS ON DELETE CASCADE);



CREATE OR REPLACE PACKAGE PROCEDIMIENTOS_PROYECTO IS
PROCEDURE INSERT_CATEGORIA (P_TITULO IN CATEGORIAS.TITULO%TYPE,
			                      P_IDCAT OUT NUMBER);

PROCEDURE INSERT_PREGUNTA(P_ENUNCIADO IN PREGUNTAS.ENUNCIADO%TYPE, 
                          P_TITULO IN CATEGORIAS.TITULO%TYPE, 
                          P_IDPREG OUT NUMBER);

PROCEDURE INSERT_RESPUESTA(P_RESPUESTA RESPUESTAS.RESPUESTA%TYPE,
                           P_ACERTADA RESPUESTAS.ACERTADA%TYPE,
                           P_IDPREG RESPUESTAS.PREGUNTA_ID_CAT%TYPE,
                           P_IDRES OUT NUMBER);

PROCEDURE UPDATE_CATEGORIA (P_TITULOVIEJO IN CATEGORIAS.TITULO%TYPE, 
			                      P_TITULONUEVO IN CATEGORIAS.TITULO%TYPE);

PROCEDURE UPDATE_PREGUNTA (P_IDPREG IN PREGUNTAS.ID_PREG%TYPE, 
                           P_ENUNCIADO IN PREGUNTAS.ENUNCIADO%TYPE, 
                          P_IDCATPREG IN PREGUNTAS.CATEGORIA_ID_PREG%TYPE);

PROCEDURE UPDATE_RESPUESTA (P_IDRESP IN RESPUESTAS.ID_RESP%TYPE, 
                           P_RESPUESTA IN RESPUESTAS.RESPUESTA%TYPE, 
                           P_ACERTADA IN RESPUESTAS.ACERTADA%TYPE);

PROCEDURE DELETE_CATEGORIA (P_IDCAT IN CATEGORIAS.ID_CAT%TYPE);

PROCEDURE DELETE_PREGUNTA (P_IDPREG IN PREGUNTAS.ID_PREG%TYPE);

PROCEDURE DELETE_RESPUESTA (P_IDRESP IN RESPUESTAS.ID_RESP%TYPE);


END;
/   

CREATE OR REPLACE PACKAGE BODY PROCEDIMIENTOS_PROYECTO IS

PROCEDURE INSERT_CATEGORIA (P_TITULO IN CATEGORIAS.TITULO%TYPE,
                            P_IDCAT OUT NUMBER)
                            
IS

V_ULTIMA_CAT CATEGORIAS.ID_CAT%TYPE;

BEGIN
SELECT MAX(ID_CAT)INTO V_ULTIMA_CAT FROM CATEGORIAS;

IF V_ULTIMA_CAT IS NULL THEN
V_ULTIMA_CAT := 1;
ELSE
V_ULTIMA_CAT := V_ULTIMA_CAT + 1;
END IF;


INSERT INTO CATEGORIAS VALUES(V_ULTIMA_CAT, P_TITULO);
P_IDCAT := V_ULTIMA_CAT; 


COMMIT;

EXCEPTION 

WHEN DUP_VAL_ON_INDEX THEN
RAISE_APPLICATION_ERROR(-20001, 'el título ya existe');
            
END INSERT_CATEGORIA;


PROCEDURE INSERT_PREGUNTA(P_ENUNCIADO IN PREGUNTAS.ENUNCIADO%TYPE, 
                          P_TITULO IN CATEGORIAS.TITULO%TYPE, 
                          P_IDPREG OUT NUMBER)

IS

V_IDCAT PREGUNTAS.CATEGORIA_ID_PREG%TYPE;

BEGIN

SELECT MAX(ID_PREG) INTO P_IDPREG FROM PREGUNTAS;
IF P_IDPREG IS NULL THEN
P_IDPREG := 1;
ELSE 
P_IDPREG := P_IDPREG + 1;
END IF;

SELECT ID_CAT INTO V_IDCAT FROM CATEGORIAS WHERE TITULO=P_TITULO;

INSERT INTO PREGUNTAS VALUES (P_IDPREG, P_ENUNCIADO, V_IDCAT);
COMMIT;


 
END INSERT_PREGUNTA;


PROCEDURE INSERT_RESPUESTA(P_RESPUESTA IN RESPUESTAS.RESPUESTA%TYPE,
                           P_ACERTADA IN RESPUESTAS.ACERTADA%TYPE,
                           P_IDPREG IN RESPUESTAS.PREGUNTA_ID_CAT%TYPE,
                           P_IDRES OUT NUMBER)
                           
IS

BEGIN
SELECT MAX(ID_RESP) INTO P_IDRES FROM RESPUESTAS;

IF P_IDRES IS NULL THEN
P_IDRES := 1;
ELSE 
P_IDRES := P_IDRES + 1;
END IF; 

INSERT INTO RESPUESTAS VALUES (P_IDRES, P_RESPUESTA, P_ACERTADA, P_IDPREG);
COMMIT;

END INSERT_RESPUESTA;



PROCEDURE UPDATE_CATEGORIA (P_TITULOVIEJO IN CATEGORIAS.TITULO%TYPE, 
			                      P_TITULONUEVO IN CATEGORIAS.TITULO%TYPE)

IS 
BEGIN
UPDATE CATEGORIAS 
SET TITULO = P_TITULONUEVO 
WHERE TITULO = P_TITULOVIEJO;
COMMIT;

END UPDATE_CATEGORIA;


PROCEDURE UPDATE_PREGUNTA (P_IDPREG IN PREGUNTAS.ID_PREG%TYPE, 
                          P_ENUNCIADO IN PREGUNTAS.ENUNCIADO%TYPE, 
                          P_IDCATPREG IN PREGUNTAS.CATEGORIA_ID_PREG%TYPE)

IS
BEGIN
UPDATE PREGUNTAS 
SET ENUNCIADO = P_ENUNCIADO, CATEGORIA_ID_PREG = P_IDCATPREG          
WHERE ID_PREG = P_IDPREG;
COMMIT; 

END UPDATE_PREGUNTA;


PROCEDURE UPDATE_RESPUESTA (P_IDRESP IN RESPUESTAS.ID_RESP%TYPE, 
                            P_RESPUESTA IN RESPUESTAS.RESPUESTA%TYPE, 
                            P_ACERTADA IN RESPUESTAS.ACERTADA%TYPE)

IS
BEGIN
UPDATE RESPUESTAS
SET RESPUESTA = P_RESPUESTA, ACERTADA = P_ACERTADA
WHERE ID_RESP = P_IDRESP;
COMMIT;

END UPDATE_RESPUESTA;


PROCEDURE DELETE_CATEGORIA (P_IDCAT IN CATEGORIAS.ID_CAT%TYPE) 
IS
BEGIN
DELETE FROM CATEGORIAS 
WHERE ID_CAT = P_IDCAT;

END DELETE_CATEGORIA;

PROCEDURE DELETE_PREGUNTA (P_IDPREG PREGUNTAS.ID_PREG%TYPE)
IS
BEGIN
DELETE FROM PREGUNTAS 
WHERE ID_PREG = P_IDPREG;

END DELETE_PREGUNTA;

PROCEDURE DELETE_RESPUESTA (P_IDRESP RESPUESTAS.ID_RESP%TYPE)
IS
BEGIN
DELETE FROM RESPUESTAS
WHERE ID_RESP = P_IDRESP;

END DELETE_RESPUESTA;



END PROCEDIMIENTOS_PROYECTO;
/



